// Card fronts that can be revealed: [PL number, rarity tier, hint type it matches, clans of the primates drawn on it
// (by fur colour; [] = no primate: items, tactics, places), name]. PL-119..148 are clan variants of the common
// Attack/Defense cards (same art, the primate in another clan).
export const FRONTS = Object.freeze([
  [1, 'legendary', 'evasion', ['ghost'], "WEEPING PHANTOM"],
  [2, 'epic', 'attack', ['rainbowe'], "PRISM DUELIST"],
  [3, 'rare', 'healing', ['purple'], "VOID ALCHEMIST"],
  [4, 'rare', 'evasion', ['pink'], "SAKURA WINDWALKER"],
  [5, 'common', 'defense', ['pink'], "TREMBLING BLOSSOM"],
  [6, 'legendary', 'attack', ['brown'], "CRIMSON RONIN"],
  [7, 'common', 'evasion', ['brown'], "SKY DISCIPLE"],
  [8, 'common', 'defense', ['brown'], "FORGE DISCIPLE"],
  [9, 'rare', 'attack', ['black'], "ONYX RECRUIT"],
  [10, 'legendary', 'attack', [], "GOLDEN KATANA"],
  [11, 'epic', 'defense', [], "VALLEY KABUTO"],
  [12, 'rare', 'healing', [], "BLADE LOCK"],
  [13, 'legendary', 'attack', ['brown'], "KI ASCENSION"],
  [14, 'common', 'evasion', ['brown'], "VALLEY PILGRIM"],
  [15, 'rare', 'defense', ['brown'], "CLIFFSIDE SAGE"],
  [16, 'epic', 'attack', ['black'], "STORM GAZE"],
  [17, 'legendary', 'healing', ['rainbowe'], "PRISM LOTUS"],
  [18, 'epic', 'healing', ['purple'], "VOID GATE"],
  [19, 'epic', 'evasion', ['pink'], "PETAL STORM"],
  [20, 'rare', 'defense', ['brown'], "TORII SENTINEL"],
  [21, 'legendary', 'defense', ['ghost'], "THE HOLLOW EMPEROR"],
  [22, 'rare', 'attack', ['brown'], "EARTHSPLITTER"],
  [23, 'rare', 'evasion', ['black'], "ROOFTOP SHADOW"],
  [24, 'common', 'defense', ['pink'], "COLD SWEAT"],
  [25, 'epic', 'evasion', ['ghost'], "FROZEN TEARS"],
  [26, 'epic', 'evasion', ['brown'], "PROPELLER SCOUT"],
  [27, 'rare', 'healing', ['black','brown'], "BOUNTY"],
  [28, 'common', 'healing', ['brown'], "STEAMING RAMEN"],
  [29, 'epic', 'healing', [], "DOJO BOOK"],
  [30, 'common', 'healing', ['brown'], "RYO POUCH"],
  [31, 'common', 'healing', ['pink'], "ONIGIRI"],
  [32, 'rare', 'healing', [], "OMAMORI"],
  [33, 'common', 'healing', ['brown'], "SAKE OF COURAGE"],
  [34, 'epic', 'evasion', ['black','pink'], "AVOID"],
  [35, 'epic', 'evasion', ['brown'], "2X"],
  [36, 'legendary', 'evasion', ['black'], "REVERSAL"],
  [37, 'rare', 'evasion', ['pink','black'], "STILLNESS"],
  [38, 'rare', 'evasion', ['black','pink'], "AMBUSH"],
  [39, 'epic', 'defense', [], "WIKO"],
  [40, 'rare', 'defense', ['brown'], "SAAKARA EXILES"],
  [41, 'legendary', 'defense', [], "GWIMUN'S EYE"],
  [42, 'legendary', 'defense', [], "NINE KI ORBS"],
  [43, 'legendary', 'attack', ['brown','black'], "THUNDER CLASH"],
  [44, 'epic', 'attack', ['brown'], "INFERNO BLADE"],
  [45, 'epic', 'evasion', ['pink'], "MOON LEAP"],
  [46, 'rare', 'defense', ['brown','black'], "BROTHERS IN ARMS"],
  [47, 'rare', 'evasion', ['brown'], "FALLEN WARRIOR"],
  [48, 'epic', 'defense', ['black','brown','pink','ghost'], "CLAN PROCESSION"],
  [49, 'epic', 'healing', ['golden-ape'], "GOLDEN SENSEI"],
  [50, 'legendary', 'attack', ['orange'], "EMBER WARMASTER"],
  [51, 'common', 'evasion', ['orange'], "EMBER SCOUT"],
  [52, 'rare', 'attack', ['golden-ape'], "GOLDEN ARCHER"],
  [53, 'rare', 'defense', ['purple'], "RAIN RONIN"],
  [54, 'common', 'defense', ['ghost'], "MOONLIT FISHER"],
  [55, 'rare', 'healing', ['pink'], "TEA MASTER"],
  [56, 'rare', 'evasion', ['black'], "ROOFTOP RUNNER"],
  [57, 'epic', 'defense', ['brown'], "WATERFALL MONK"],
  [58, 'epic', 'attack', ['brown'], "BACK TO BACK"],
  [59, 'rare', 'attack', ['rainbowe'], "PRISM SPEARMAN"],
  [60, 'common', 'defense', ['golden-ape'], "BANNER BEARER"],
  [61, 'common', 'defense', ['brown'], "SLEEPING GUARDIAN"],
  [62, 'common', 'healing', ['orange'], "LANTERN KEEPER"],
  [63, 'rare', 'healing', ['purple'], "STARGAZER"],
  [64, 'rare', 'attack', ['ghost'], "TAIKO DRUMMER"],
  [65, 'epic', 'evasion', ['pink'], "FAN DANCER"],
  [66, 'epic', 'attack', ['black'], "CEILING ASSASSIN"],
  [67, 'rare', 'healing', ['golden-ape','pink'], "FESTIVAL TWINS"],
  [68, 'common', 'evasion', ['brown'], "CLIFF CLIMBER"],
  [69, 'common', 'healing', ['brown'], "RIVER FERRYMAN"],
  [70, 'rare', 'defense', ['ghost'], "ICE SENTINEL"],
  [71, 'epic', 'attack', ['orange'], "EMBER BERSERKER"],
  [72, 'epic', 'healing', ['purple','golden-ape'], "LAKE OF ECHOES"],
  [73, 'legendary', 'defense', ['golden-ape'], "GOLDEN SHOGUN"],
  [74, 'common', 'evasion', ['pink'], "BLOSSOM SWING"],
  [75, 'rare', 'evasion', ['black'], "SILENT BOW"],
  [76, 'common', 'healing', ['brown'], "HOT STEW"],
  [77, 'legendary', 'evasion', ['rainbowe'], "PRISM ECHO"],
  [78, 'epic', 'defense', ['pink','black','brown','golden-ape'], "FIREWORKS NIGHT"],
  [79, 'legendary', 'attack', ['golden-ape'], "SOLAR WAVE"],
  [80, 'epic', 'attack', ['orange'], "AWAKENED FURY"],
  [81, 'legendary', 'healing', ['ghost'], "SPIRIT ORB"],
  [82, 'epic', 'attack', ['rainbowe','purple'], "BEAM CLASH"],
  [83, 'epic', 'attack', ['golden-ape','orange'], "SKY CLASH"],
  [84, 'common', 'evasion', ['pink'], "TREETOP LEAP"],
  [85, 'common', 'healing', ['pink'], "LOVE LETTER"],
  [86, 'rare', 'defense', ['pink'], "PARASOL GUARD"],
  [87, 'common', 'attack', ['red-hair'], "RONIN'S ROAD"],
  [88, 'epic', 'attack', ['red-hair'], "BLOOD MOON VOW"],
  [89, 'rare', 'attack', ['red-hair','brown'], "DAWN DUEL"],
  [90, 'common', 'defense', ['brown'], "RICE PADDY"],
  [91, 'rare', 'defense', ['brown'], "BOULDER BEARER"],
  [92, 'common', 'healing', ['brown'], "LUNCH BREAK"],
  [93, 'rare', 'evasion', ['black'], "CASTLE CLIMB"],
  [94, 'common', 'evasion', ['black'], "SMOKE BOMB"],
  [95, 'epic', 'defense', ['black'], "MOON WATCH"],
  [96, 'common', 'evasion', ['purple'], "POTION RUNNER"],
  [97, 'legendary', 'healing', ['purple'], "ECLIPSE RITUAL"],
  [98, 'rare', 'healing', ['purple'], "FIREFLY CATCHER"],
  [99, 'rare', 'evasion', ['orange'], "FIRE DANCER"],
  [100, 'common', 'defense', ['orange'], "LAVA WATCH"],
  [101, 'rare', 'healing', ['golden-ape','black','brown'], "GOLDEN LESSON"],
  [102, 'common', 'defense', ['golden-ape'], "PALACE GUARD"],
  [103, 'rare', 'evasion', ['ghost'], "SPIRIT BRIDGE"],
  [104, 'epic', 'defense', ['ghost'], "HOLLOW BELL"],
  [105, 'rare', 'healing', ['rainbowe'], "PRISM SAGE"],
  [106, 'rare', 'attack', ['rainbowe'], "RAINBOW BREATH"],
  [107, 'legendary', 'attack', [], "BLOOD MOON KATANA"],
  [108, 'rare', 'attack', [], "TWIN SHADOW BLADES"],
  [109, 'rare', 'defense', [], "LACQUER ARMOR"],
  [110, 'common', 'defense', [], "WANDERER'S KASA"],
  [111, 'epic', 'healing', [], "GOLDEN AMULET"],
  [112, 'common', 'healing', [], "SPIRIT TEA"],
  [113, 'common', 'healing', [], "DANGO"],
  [114, 'rare', 'healing', [], "WAR MAP"],
  [115, 'rare', 'evasion', ['black'], "SMOKE SCREEN"],
  [116, 'rare', 'evasion', ['red-hair','black'], "FEINT"],
  [117, 'epic', 'defense', [], "THE NINE VALLEYS"],
  [118, 'legendary', 'defense', [], "HOLLOW PALACE"],
  [119, 'common', 'defense', ['black'], "TREMBLING BLOSSOM"],
  [120, 'common', 'defense', ['brown'], "TREMBLING BLOSSOM"],
  [121, 'common', 'defense', ['red-hair'], "TREMBLING BLOSSOM"],
  [122, 'common', 'defense', ['purple'], "FORGE DISCIPLE"],
  [123, 'common', 'defense', ['orange'], "FORGE DISCIPLE"],
  [124, 'common', 'defense', ['golden-ape'], "FORGE DISCIPLE"],
  [125, 'common', 'defense', ['black'], "COLD SWEAT"],
  [126, 'common', 'defense', ['brown'], "COLD SWEAT"],
  [127, 'common', 'defense', ['red-hair'], "COLD SWEAT"],
  [128, 'common', 'defense', ['red-hair'], "MOONLIT FISHER"],
  [129, 'common', 'defense', ['pink'], "MOONLIT FISHER"],
  [130, 'common', 'defense', ['purple'], "MOONLIT FISHER"],
  [131, 'common', 'defense', ['black'], "BANNER BEARER"],
  [132, 'common', 'defense', ['brown'], "BANNER BEARER"],
  [133, 'common', 'defense', ['red-hair'], "BANNER BEARER"],
  [134, 'common', 'defense', ['purple'], "SLEEPING GUARDIAN"],
  [135, 'common', 'defense', ['orange'], "SLEEPING GUARDIAN"],
  [136, 'common', 'defense', ['golden-ape'], "SLEEPING GUARDIAN"],
  [137, 'common', 'attack', ['black'], "RONIN'S ROAD"],
  [138, 'common', 'attack', ['brown'], "RONIN'S ROAD"],
  [139, 'common', 'attack', ['pink'], "RONIN'S ROAD"],
  [140, 'common', 'defense', ['purple'], "RICE PADDY"],
  [141, 'common', 'defense', ['orange'], "RICE PADDY"],
  [142, 'common', 'defense', ['golden-ape'], "RICE PADDY"],
  [143, 'common', 'defense', ['black'], "LAVA WATCH"],
  [144, 'common', 'defense', ['brown'], "LAVA WATCH"],
  [145, 'common', 'defense', ['red-hair'], "LAVA WATCH"],
  [146, 'common', 'defense', ['pink'], "PALACE GUARD"],
  [147, 'common', 'defense', ['purple'], "PALACE GUARD"],
  [148, 'common', 'defense', ['orange'], "PALACE GUARD"]
].map(([n, rarity, type, clans, name]) => Object.freeze({ n, rarity, type, clans: Object.freeze(clans), name })));
